-- MySQL Script generated by MySQL Workbench
-- Wed Jul 31 21:02:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema swegger_crud
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `swegger_swegger_crud` ;

-- -----------------------------------------------------
-- Schema swegger_crud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swegger_swegger_crud` DEFAULT CHARACTER SET utf8 ;
USE `swegger_swegger_crud` ;

-- -----------------------------------------------------
-- Table `swegger_crud`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swegger_swegger_crud`.`profiles` ;

CREATE TABLE IF NOT EXISTS `swegger_crud`.`profiles` (
  `profile_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`profile_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swegger_crud`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swegger_swegger_crud`.`users` ;

CREATE TABLE IF NOT EXISTS `swegger_crud`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `profile_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `profile_id_users_idx` (`profile_id` ASC),
  CONSTRAINT `profile_id_users`
    FOREIGN KEY (`profile_id`)
    REFERENCES `swegger_swegger_crud`.`profiles` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `swegger_crud`.`profiles`
-- -----------------------------------------------------
START TRANSACTION;
USE `swegger_crud`;
INSERT INTO `swegger_crud`.`profiles` (`profile_id`, `name`) VALUES (1, 'ADMIN');
INSERT INTO `swegger_crud`.`profiles` (`profile_id`, `name`) VALUES (2, 'CLIENT');

COMMIT;

